#!/usr/bin/env bash
# On the Harbour host, route HARBOUR_DNS_ZONE queries to local harbour-dns (127.0.0.1).
#
# MagicDNS (100.100.100.100) returns NXDOMAIN for custom zones like harbour.<tailnet>.ts.net
# when the split-DNS resolver runs on this same machine. Phones/laptops on the tailnet still
# use split DNS normally; this fix is only for curl/browser on the server itself.
#
# Usage: sudo ./scripts/install-local-harbour-dns-resolved.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/../compose/.env"
DROP_IN="/etc/systemd/resolved.conf.d/harbour-local-dns.conf"

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root: sudo $0" >&2
  exit 1
fi

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Missing ${ENV_FILE}" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "${ENV_FILE}"
set +a

zone="${HARBOUR_DNS_ZONE:?Set HARBOUR_DNS_ZONE in compose/.env}"

mkdir -p "$(dirname "${DROP_IN}")"
cat >"${DROP_IN}" <<EOF
# Harbour split DNS — local resolver on the Harbour host (generated by install-local-harbour-dns-resolved.sh)
[Resolve]
DNS=127.0.0.1
Domains=~${zone}
EOF

systemctl restart systemd-resolved

echo "Installed ${DROP_IN}"
echo "Routing ~${zone} -> 127.0.0.1 (harbour-dns)"
echo ""
echo "Verify:"
echo "  resolvectl query ${zone}"
echo "  curl -k -I https://${zone}:8443/"
